name: Deploy Pixel Chess Backend

on:
  push:
    branches:
      - master
    paths:
      - 'backend/**'
      - '.github/workflows/deploy-backend.yml'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      # Log in to Docker Hub
      - name: Docker Hub Login
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # Build & push Docker image
      - name: Build & Push Docker Image
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/pixel-chess-backend:latest ./backend
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/pixel-chess-backend:latest

      # Authenticate to Google Cloud
      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCLOUD_KEY }}
      
      # Setup the GCloud SDK
      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{ secrets.GCLOUD_PROJECT }}

      # Deploy to Cloud Run using the dedicated action
      - name: Deploy to Cloud Run
        uses: google-github-actions/deploy-cloudrun@v2
        with:
          service: pixel-chess-backend
          region: asia-south1
          image: docker.io/${{ secrets.DOCKERHUB_USERNAME }}/pixel-chess-backend:latest
          platform: managed
          allow_unauthenticated: true
          env_vars: |
            MONGO_URI=${{ secrets.MONGO_URI }}
            NEXTAUTH_SECRET=${{ secrets.NEXTAUTH_SECRET }}
