name: Deploy Pixel Chess Backend

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      # Log in to Docker Hub
      - name: Docker Hub Login
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # Build & push Docker image
      - name: Build & Push Docker Image
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/pixel-chess-backend:latest ./backend
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/pixel-chess-backend:latest

      # Authenticate to Google Cloud
      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCLOUD_KEY }}

      # Authenticate gcloud
      - name: Set up GCP
        uses: google-github-actions/setup-gcloud@v2
        with:
          service_account_key: ${{ secrets.GCLOUD_KEY }}
          project_id: ${{ secrets.GCLOUD_PROJECT }}

      # Deploy to Cloud Run
      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy pixel-chess-backend \
            --image=docker.io/${{ secrets.DOCKERHUB_USERNAME }}/pixel-chess-backend:latest \
            --region=asia-south1 \
            --platform=managed \
            --allow-unauthenticated \
            --set-env-vars=MONGO_URI=${{ secrets.MONGO_URI }},NEXTAUTH_SECRET=${{ secrets.NEXTAUTH_SECRET }}
